name: take_my_tym_admin
description: "Take My Tym Admin side is a comprehensive dashboard for managing user data, content, and analytics for the Take My Tym application. It includes features such as real-time updates, user management, content moderation, and detailed reporting."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.2
  go_router: ^13.2.4
  lottie: ^3.1.0
  firebase_core: ^2.29.0
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.67.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_lint: ^2.3.10

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins/Poppins-Regular.ttf
        - asset: assets/font/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Poppins/Poppins-Black.ttf
          weight: 900

    - family: Denton Condensed
      fonts:
        - asset: assets/font/Denton Condensed/DentonCondensedTest-Regular.otf
        - asset: assets/font/Denton Condensed/DentonCondensedTest-Black.otf
          weight: 800
        - asset: assets/font/Denton Condensed/DentonCondensedTest-Medium.otf
          weight: 900